/* THIS FILE IS GENERATED BY A HELPER SCRIPT.*/
/* DO NOT EDIT THIS FILE DIRECTLY, AS YOUR EDITS MAY BE OVERWRITTEN. */

export const worldMapImports = {
  "world-42,48": "world_x42_y48.tmj",
  "world-42,49": "world_x42_y49.tmj",
  "world-42,50": "world_x42_y50.tmj",
  "world-43,48": "world_x43_y48.tmj",
  "world-43,49": "world_x43_y49.tmj",
  "world-43,50": "world_x43_y50.tmj",
  "world-44,48": "world_x44_y48.tmj",
  "world-44,49": "world_x44_y49.tmj",
  "world-44,50": "world_x44_y50.tmj",
  "world-45,50": "world_x45_y50.tmj",
  "world-46,50": "world_x46_y50.tmj",
  "world-46,51": "world_x46_y51.tmj",
  "world-47,50": "world_x47_y50.tmj",
  "world-47,51": "world_x47_y51.tmj",
  "world-47,52": "world_x47_y52.tmj",
  "world-48,50": "world_x48_y50.tmj",
  "world-49,50": "world_x49_y50.tmj",
  "world-50,50": "world_x50_y50.tmj",
  "world-50,51": "world_x50_y51.tmj",
  "world-50,52": "world_x50_y52.tmj",
  "world-51,49": "world_x51_y49.tmj",
  "world-51,50": "world_x51_y50.tmj",
  "world-52,50": "world_x52_y50.tmj"
};
